### ISSUE TITLE
Moving marker seems broken

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/onosm.org#134] opened 2024-01-19 17:53 UTC
https://community.openstreetmap.org/t/osm-notes-around-the-tehran-node/108248/10

![Peek 2024-01-19 18-53](https://github.com/osmlab/onosm.org/assets/899988/1fb9e913-9bdb-48c8-86ca-7b61382156fa)

> https://www.onosm.org/ first asks where your business is located. It then tries to geocode whatever you type.

> If it doesn’t find it (I tried it with 123 Doesn’t Exist Street, Tehran, Iran), it says: “We couldn’t find your address. Try searching for your street or city without the address.”

> If you do as suggested and put the city name, then click continue, it’ll put the note where the place node is.

> It does say “Click and drag the marker on your business place position” but that doesn’t work for me. It doesn’t let me move the marker.

**Comment by daganzdaanda** [comment] 2024-01-29 01:42
See also #127 and #129

**Comment by iandees** [comment] 2024-01-29 03:25
I'm going to close this as a dupe of #127. Thank you for the animated GIF to reproduce, though!

**Closed as completed by iandees** 2024-01-29 03:25 UTC
