### ISSUE TITLE
Iran situation

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/onosm.org#124] opened 2023-09-04 04:57 UTC
Iran overall is spammed with onosm.org notes, to the point of killing note feature there, see https://resultmaps.neis-one.org/osm-notes-country?c=Iran

![screen02](https://github.com/osmlab/onosm.org/assets/899988/2f85be89-db7c-4815-9e2a-ae83ce3800d7)

See also #121 and  #103

Last month about 13 000  old notes in Iran were mass-closed with a script by someone, due to onosm.org note wave.

**Comment by iandees** [comment] 2023-09-04 04:59
Dupe of #103

**Comment by matkoniecz** [comment] 2023-09-04 05:00
> Dupe of https://github.com/osmlab/onosm.org/issues/103

No, as many of them are in Iran - with so high activity that they killed note feature in Iran

**Closed as completed by iandees** 2023-09-04 04:59 UTC

**Comment by matkoniecz** [comment] 2023-09-04 05:00
Maybe it would be a good idea to block futher onosm.org notes in Iran until this notes are processed?

Right now whoever does this manually wastes time (or is completely misguided if they do it automatically) and makes much harder to process real notes.

**Comment by iandees** [comment] 2023-09-04 05:31
I'm grouping all the "lots of notes in the wrong spot" issues into #103, simply because that's where most of the discussion has been happening.

**Comment by matkoniecz** [comment] 2023-09-04 07:35
(1) then maybe changing title would be a good idea? I searched whether it was reported, seen that, not even opened it as title was about something clearly different

(2) it is not merely about "many notes at a single location" - it is about confused/too large scale/misautomated use of onosm.org swamping any other notes in Iran and ending as a huge waste for everyone (whoever makes them whoever mass closes them, whoever processes notes)

**Comment by iandees** [comment] 2023-09-04 12:21
> then maybe changing title would be a good idea?

I changed the title of 103. The reason I replied to this and other tickets was to redirect people who might come upon these tickets (that perhaps match their search terms better).

> it is about confused/too large scale/misautomated use of onosm.org swamping any other notes in Iran and ending as a huge waste for everyone

I am redirecting people because I think a solution to the problem you mention is to fix the bug that makes it easy to generate Notes in the wrong spot with onosm.org.

**Comment by matkoniecz** [comment] 2023-09-04 20:47
> I am redirecting people because I think a solution to the problem you mention is to fix the bug that makes it easy to generate Notes in the wrong spot with onosm.org.

How it will fix problem of creating tens of thousands of notes in Iran, beyond any capacity of mappers active there?

**Comment by iandees** [comment] 2023-09-04 21:16
Lots of people suggesting data improvements to OSM is not a problem.

**Comment by matkoniecz** [comment] 2023-09-05 08:21
It is a problem when people processing notes are overwhelmed by huge volume.

It can easily result in situation where people start ignoring note feature completely if it is overwhelming. Low quality notes can make it even worse.

**Comment by ahangarha** [comment] 2024-02-14 12:19
I am from Iran, and my name is in the screenshot.

I don't think these notes are spam. Many people come to add their businesses on the map because there are map services in Iran using OSM, and people want them to have their businesses.
